### Create Cred without any cert
POST http://localhost:8000/status  HTTP/1.1
Content-Type: application/json

{
  "fullName":"Vitor Pamplona", 
  "dob":"1922-07-27"
}

### DCC with 2 doses
POST http://localhost:8000/hc1status  HTTP/1.1
Content-Type: application/json

{
  "qr":"HC1:NCFOXN%TSMAHN-H3O4:PVH AJ2J$9J0II:Q5 43SLG/EBUD2XPO.TM8W42YBJSRQHIZC4.OI1RM8ZA*LPUY29+KCFF-+K*LPH*AA:G$LO5/A+*39UVC 0G8C:USOHDAPSY+3AZ33M3JZIM-1Z.4UX4795L*KDYPWGO+9AAEOXCRFE4IWMIT5NR7LY4357LC4DK4LC6DQ42JO9X7M16GF6:/6N9R%EP3/28MJE9A7EDA.D90I/EL6KKLIIL4OTJLI C3DE0OA0D9E2LBHHGKLO-K%FGLIA-D8+6JDJN XGHFEZI9$JAQJKHJLK3M484SZ4RZ4E%5MK9AZPKD70/LIFN7KTC5NI%KH NVFWJ-SUQK8%MPLI8:31CRNHS*44+4BM.SY$NOXAJ8CTAP1-ST*QGTA4W7.Y7N31D6K-BW/ N NRM1U*HFNHJ9USSK380E%WISO9+%GRTJ GBW0UEFJ42SUTU9I8/MD3N3ARC/03W-RHDMO1VC767.P95G-CFA.7L C02FM8F6UF"
}

### DCC with 1 doses
POST http://localhost:8000/hc1status  HTTP/1.1
Content-Type: application/json

{
  "qr":"HC1:6BFF80W80T9WTWGSLKC 4769R174TF//5P30FBBHB4WY0VCC9/TFN0NAD2Q1*70J+9D97TK0F90$PC5$CUZC $5Y$5TPCBEC7ZKW.C$$EE/44LEJXOF/D234U44CECT34AEC1$C JCA/DY+8CEC2XO 3EAPEKI9CECLPCG/DGEERB8.NAQ+9BS7NB8.R7LB8CY8MPCG/DT D.HAA+921ANNAXH9NB8JPCT3E6JD646CA78465W5X577:EDOL9WEQDD+Q6TW6FA7C466KCN9E%961A6DL6FA7D46.JCP9EJY8L/5M/5546.96VF6.JCBECB1A-:8$966469L6OF6VX6FVC*70KQEPD0LVC6JD846Y96B463W5VX6UPCBJCOT9+ED83EZED+EDKWE3EFX3E/34Z1BWJC0FD4X4:KEPH7M/ESDD746VG7TS9 6A1B8MZAHNA356TR6/IBV+A2T9Z%6ZB827BJ6F4*AX48WJDZ%1TJHC0Q/TFLX67MHSFT-%0JELBSOC4V+XIK9CW3PDIN7886IIRWL-WQ2-9A-9%QJ*DMPHMCNH%ZR0%U7:JXJD-3H"
}


### DCC with 3 doses
POST http://localhost:8000/hc1status HTTP/1.1
Content-Type: application/json

{
  "qr":"HC1:6BFOXN%TSMAHN-H+XO5XF7:UY%FJ.G0IIXLHKHR6H2LDSOIMI%C9 SLAP9.SURC/GPWBI$C9UDBQEAJJKIIIEC8.-B97U: K8*NHQ2VAP1US1Q7OKHHUEPOP%WUXQ72QETZU3UQRVULKHWWU:16Q8Q*7R-PP9$PB/9OK5JWEMN1/9VSL1Y813.UNNUR+UK0VF/94O5%ZE/NEVTEJAVX5NGTUY*U9/9-3APF6:66A$QX76LZ6Q59YPDN*I4OIMEDTJCJKDLEDL9CZTAKBI/8D:8DKTDL+S/15A+2XEN QT QTHC31M3+E3+T4D-4HRVUMNMD3323623423.LJX/KS968X2+36/-KW10SW6A$Q836BPK$*SQDKVLI7VHB$FNXUJRH0LH%Y2 UQ/RONSGWLIML5YO9OUUMK9WLIK*L5R1G-VOXL2VFLW5BWOM-PDNK7NGXH43R3/YF9$R2SK3S3:BO5Y5N3W5/UZ1T4+R8F4SF91.JYRSF+J6:L$XNRBEZ.MMC4TBQ $D-8RS7FE7BH7T/*S4 KWSDNQIS.123K$*SB$BI/O:I8PXLQH1/HN:UG"
}
